// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock/stock_fetcher_manager.proto

package stock_fetcher_manager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockPriceRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPriceRequest) Reset()         { *m = StockPriceRequest{} }
func (m *StockPriceRequest) String() string { return proto.CompactTextString(m) }
func (*StockPriceRequest) ProtoMessage()    {}
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_fetcher_manager_5e794c1b34bf40de, []int{0}
}
func (m *StockPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceRequest.Unmarshal(m, b)
}
func (m *StockPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceRequest.Marshal(b, m, deterministic)
}
func (dst *StockPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceRequest.Merge(dst, src)
}
func (m *StockPriceRequest) XXX_Size() int {
	return xxx_messageInfo_StockPriceRequest.Size(m)
}
func (m *StockPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceRequest proto.InternalMessageInfo

func (m *StockPriceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type StockPriceResponse struct {
	Prices               string   `protobuf:"bytes,1,opt,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPriceResponse) Reset()         { *m = StockPriceResponse{} }
func (m *StockPriceResponse) String() string { return proto.CompactTextString(m) }
func (*StockPriceResponse) ProtoMessage()    {}
func (*StockPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_fetcher_manager_5e794c1b34bf40de, []int{1}
}
func (m *StockPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceResponse.Unmarshal(m, b)
}
func (m *StockPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceResponse.Marshal(b, m, deterministic)
}
func (dst *StockPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceResponse.Merge(dst, src)
}
func (m *StockPriceResponse) XXX_Size() int {
	return xxx_messageInfo_StockPriceResponse.Size(m)
}
func (m *StockPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceResponse proto.InternalMessageInfo

func (m *StockPriceResponse) GetPrices() string {
	if m != nil {
		return m.Prices
	}
	return ""
}

func init() {
	proto.RegisterType((*StockPriceRequest)(nil), "StockPriceRequest")
	proto.RegisterType((*StockPriceResponse)(nil), "StockPriceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StockFetchManagerClient is the client API for StockFetchManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockFetchManagerClient interface {
	GetStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error)
}

type stockFetchManagerClient struct {
	cc *grpc.ClientConn
}

func NewStockFetchManagerClient(cc *grpc.ClientConn) StockFetchManagerClient {
	return &stockFetchManagerClient{cc}
}

func (c *stockFetchManagerClient) GetStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error) {
	out := new(StockPriceResponse)
	err := c.cc.Invoke(ctx, "/StockFetchManager/GetStockPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockFetchManagerServer is the server API for StockFetchManager service.
type StockFetchManagerServer interface {
	GetStockPrice(context.Context, *StockPriceRequest) (*StockPriceResponse, error)
}

func RegisterStockFetchManagerServer(s *grpc.Server, srv StockFetchManagerServer) {
	s.RegisterService(&_StockFetchManager_serviceDesc, srv)
}

func _StockFetchManager_GetStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockFetchManagerServer).GetStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockFetchManager/GetStockPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockFetchManagerServer).GetStockPrice(ctx, req.(*StockPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockFetchManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StockFetchManager",
	HandlerType: (*StockFetchManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockPrice",
			Handler:    _StockFetchManager_GetStockPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/stock_fetcher_manager.proto",
}

func init() {
	proto.RegisterFile("stock/stock_fetcher_manager.proto", fileDescriptor_stock_fetcher_manager_5e794c1b34bf40de)
}

var fileDescriptor_stock_fetcher_manager_5e794c1b34bf40de = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x2e, 0xc9, 0x4f,
	0xce, 0xd6, 0x07, 0x93, 0xf1, 0x69, 0xa9, 0x25, 0xc9, 0x19, 0xa9, 0x45, 0xf1, 0xb9, 0x89, 0x79,
	0x89, 0xe9, 0xa9, 0x45, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9,
	0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9,
	0x79, 0xc5, 0x10, 0x59, 0x25, 0x6d, 0x2e, 0xc1, 0x60, 0x90, 0xe6, 0x80, 0xa2, 0xcc, 0xe4, 0xd4,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xca, 0xdc, 0xa4, 0xfc,
	0x1c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0x49, 0x87, 0x4b, 0x08, 0x59, 0x71,
	0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x48, 0x75, 0x01, 0x48, 0xa0, 0x18, 0xa6, 0x1a, 0xc2, 0x33,
	0xca, 0x83, 0x1a, 0xed, 0x06, 0x72, 0x96, 0x2f, 0xc4, 0x4d, 0x42, 0x91, 0x5c, 0xbc, 0xee, 0xa9,
	0x25, 0x08, 0x53, 0x84, 0x84, 0xf4, 0x30, 0xec, 0x97, 0x12, 0xd6, 0xc3, 0xb4, 0x46, 0x49, 0xbe,
	0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x92, 0x42, 0xe2, 0x60, 0x9f, 0x94, 0x19, 0xea, 0xa7, 0xa7, 0x96,
	0xc4, 0x43, 0x3c, 0x0e, 0xb6, 0x30, 0x89, 0x0d, 0xec, 0x23, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb1, 0xb6, 0xdf, 0x2a, 0x14, 0x01, 0x00, 0x00,
}
