// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stock/stock_fetcher_manager.proto

package stock_fetcher_manager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StockPriceRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPriceRequest) Reset()         { *m = StockPriceRequest{} }
func (m *StockPriceRequest) String() string { return proto.CompactTextString(m) }
func (*StockPriceRequest) ProtoMessage()    {}
func (*StockPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_fetcher_manager_ff51a6e0c9a855b1, []int{0}
}
func (m *StockPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceRequest.Unmarshal(m, b)
}
func (m *StockPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceRequest.Marshal(b, m, deterministic)
}
func (dst *StockPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceRequest.Merge(dst, src)
}
func (m *StockPriceRequest) XXX_Size() int {
	return xxx_messageInfo_StockPriceRequest.Size(m)
}
func (m *StockPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceRequest proto.InternalMessageInfo

func (m *StockPriceRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type StockPriceResponse struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// time to price
	Prices               map[string]*StockPrice `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StockPriceResponse) Reset()         { *m = StockPriceResponse{} }
func (m *StockPriceResponse) String() string { return proto.CompactTextString(m) }
func (*StockPriceResponse) ProtoMessage()    {}
func (*StockPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_fetcher_manager_ff51a6e0c9a855b1, []int{1}
}
func (m *StockPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPriceResponse.Unmarshal(m, b)
}
func (m *StockPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPriceResponse.Marshal(b, m, deterministic)
}
func (dst *StockPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPriceResponse.Merge(dst, src)
}
func (m *StockPriceResponse) XXX_Size() int {
	return xxx_messageInfo_StockPriceResponse.Size(m)
}
func (m *StockPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockPriceResponse proto.InternalMessageInfo

func (m *StockPriceResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *StockPriceResponse) GetPrices() map[string]*StockPrice {
	if m != nil {
		return m.Prices
	}
	return nil
}

type StockPrice struct {
	Open                 float64  `protobuf:"fixed64,1,opt,name=Open,proto3" json:"Open,omitempty"`
	High                 float64  `protobuf:"fixed64,2,opt,name=High,proto3" json:"High,omitempty"`
	Low                  float64  `protobuf:"fixed64,3,opt,name=Low,proto3" json:"Low,omitempty"`
	Close                float64  `protobuf:"fixed64,4,opt,name=Close,proto3" json:"Close,omitempty"`
	Volumn               uint64   `protobuf:"varint,5,opt,name=volumn,proto3" json:"volumn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockPrice) Reset()         { *m = StockPrice{} }
func (m *StockPrice) String() string { return proto.CompactTextString(m) }
func (*StockPrice) ProtoMessage()    {}
func (*StockPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_stock_fetcher_manager_ff51a6e0c9a855b1, []int{2}
}
func (m *StockPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockPrice.Unmarshal(m, b)
}
func (m *StockPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockPrice.Marshal(b, m, deterministic)
}
func (dst *StockPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockPrice.Merge(dst, src)
}
func (m *StockPrice) XXX_Size() int {
	return xxx_messageInfo_StockPrice.Size(m)
}
func (m *StockPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_StockPrice.DiscardUnknown(m)
}

var xxx_messageInfo_StockPrice proto.InternalMessageInfo

func (m *StockPrice) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *StockPrice) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *StockPrice) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *StockPrice) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *StockPrice) GetVolumn() uint64 {
	if m != nil {
		return m.Volumn
	}
	return 0
}

func init() {
	proto.RegisterType((*StockPriceRequest)(nil), "StockPriceRequest")
	proto.RegisterType((*StockPriceResponse)(nil), "StockPriceResponse")
	proto.RegisterMapType((map[string]*StockPrice)(nil), "StockPriceResponse.PricesEntry")
	proto.RegisterType((*StockPrice)(nil), "StockPrice")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StockFetchManagerClient is the client API for StockFetchManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockFetchManagerClient interface {
	GetStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error)
}

type stockFetchManagerClient struct {
	cc *grpc.ClientConn
}

func NewStockFetchManagerClient(cc *grpc.ClientConn) StockFetchManagerClient {
	return &stockFetchManagerClient{cc}
}

func (c *stockFetchManagerClient) GetStockPrice(ctx context.Context, in *StockPriceRequest, opts ...grpc.CallOption) (*StockPriceResponse, error) {
	out := new(StockPriceResponse)
	err := c.cc.Invoke(ctx, "/StockFetchManager/GetStockPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockFetchManagerServer is the server API for StockFetchManager service.
type StockFetchManagerServer interface {
	GetStockPrice(context.Context, *StockPriceRequest) (*StockPriceResponse, error)
}

func RegisterStockFetchManagerServer(s *grpc.Server, srv StockFetchManagerServer) {
	s.RegisterService(&_StockFetchManager_serviceDesc, srv)
}

func _StockFetchManager_GetStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockFetchManagerServer).GetStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockFetchManager/GetStockPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockFetchManagerServer).GetStockPrice(ctx, req.(*StockPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockFetchManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StockFetchManager",
	HandlerType: (*StockFetchManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockPrice",
			Handler:    _StockFetchManager_GetStockPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/stock_fetcher_manager.proto",
}

func init() {
	proto.RegisterFile("stock/stock_fetcher_manager.proto", fileDescriptor_stock_fetcher_manager_ff51a6e0c9a855b1)
}

var fileDescriptor_stock_fetcher_manager_ff51a6e0c9a855b1 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0xd3, 0x0f, 0x70, 0x82, 0xa0, 0xab, 0x68, 0x2c, 0x42, 0xd3, 0x9c, 0x02, 0x42, 0x82,
	0xf5, 0xa0, 0x78, 0x15, 0xab, 0x07, 0x45, 0x89, 0x27, 0x4f, 0x65, 0x5b, 0xc6, 0x34, 0x34, 0xdd,
	0x89, 0xd9, 0x6d, 0xa5, 0x57, 0xff, 0x82, 0xbf, 0xc3, 0x5f, 0xe3, 0x5f, 0xf0, 0x87, 0xc8, 0x6e,
	0x02, 0x06, 0xaa, 0x97, 0x30, 0xef, 0xcd, 0x9b, 0x97, 0xe4, 0x3d, 0x18, 0x28, 0x4d, 0xd3, 0x79,
	0x6c, 0x9f, 0xe3, 0x17, 0xd4, 0xd3, 0x19, 0x96, 0xe3, 0x85, 0x90, 0x22, 0xc5, 0x32, 0x2a, 0x4a,
	0xd2, 0xd4, 0x3b, 0x4e, 0x89, 0xd2, 0x1c, 0x63, 0x51, 0x64, 0xb1, 0x90, 0x92, 0xb4, 0xd0, 0x19,
	0x49, 0x55, 0x6d, 0x83, 0x13, 0xd8, 0x7d, 0x32, 0xc7, 0x8f, 0x65, 0x36, 0xc5, 0x04, 0x5f, 0x97,
	0xa8, 0x34, 0x3f, 0x80, 0xae, 0x5a, 0x2f, 0x26, 0x94, 0x7b, 0xcc, 0x67, 0xe1, 0x56, 0x52, 0xa3,
	0xe0, 0x93, 0x01, 0x6f, 0xaa, 0x55, 0x41, 0x52, 0xe1, 0x7f, 0x72, 0x7e, 0x0e, 0xdd, 0xc2, 0x08,
	0x95, 0xe7, 0xf8, 0xad, 0xd0, 0x1d, 0xf6, 0xa3, 0xcd, 0xe3, 0xc8, 0x22, 0x75, 0x2d, 0x75, 0xb9,
	0x4e, 0x6a, 0x79, 0x6f, 0x04, 0x6e, 0x83, 0xe6, 0x3b, 0xd0, 0x9a, 0xe3, 0xba, 0x36, 0x37, 0x23,
	0x1f, 0x40, 0x67, 0x25, 0xf2, 0x25, 0x7a, 0x8e, 0xcf, 0x42, 0x77, 0xe8, 0x36, 0x8d, 0xab, 0xcd,
	0xa5, 0x73, 0xc1, 0x02, 0x0d, 0xf0, 0xbb, 0xe0, 0x1c, 0xda, 0x0f, 0x05, 0x4a, 0xeb, 0xc3, 0x12,
	0x3b, 0x1b, 0xee, 0x36, 0x4b, 0x67, 0xd6, 0x87, 0x25, 0x76, 0x36, 0xaf, 0xbb, 0xa3, 0x37, 0xaf,
	0x65, 0x29, 0x33, 0xf2, 0x7d, 0xe8, 0x5c, 0xe5, 0xa4, 0xd0, 0x6b, 0x5b, 0xae, 0x02, 0xe6, 0xb7,
	0x57, 0x94, 0x2f, 0x17, 0xd2, 0xeb, 0xf8, 0x2c, 0x6c, 0x27, 0x35, 0x1a, 0xca, 0x3a, 0xd2, 0x91,
	0xa9, 0xe3, 0xbe, 0xea, 0x82, 0x3f, 0xc3, 0xf6, 0x0d, 0xea, 0xe6, 0xd7, 0x44, 0x1b, 0xb9, 0xf7,
	0xf6, 0xfe, 0x08, 0x28, 0xe8, 0xbf, 0x7f, 0x7d, 0x7f, 0x38, 0x47, 0xfc, 0xd0, 0x36, 0xb8, 0x3a,
	0x8d, 0x53, 0xd4, 0xe3, 0xaa, 0x70, 0x1b, 0xd7, 0xa4, 0x6b, 0x9b, 0x3c, 0xfb, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x81, 0xca, 0xe7, 0x0e, 0x0c, 0x02, 0x00, 0x00,
}
